/**
 * Official road border / customs posts relevant to these trips.
 * Schengen-internal EU (CZ–DE, SK–HU, …) omitted — no Zoll.
 * Norway is Schengen but not EU → customs at NO–SE.
 */
export const BORDER_CATALOG = [
  // HU–RS
  {
    id: "roszke-horgos",
    name: "Röszke / Horgoš (dálnice M5/A1)",
    query: "Horgos Roszke border crossing A1",
    pair: "HU-RS",
    openingHoursLabel: "Nonstop (24/7)",
    note: "Mezinárodní osobní i nákladní provoz, dálnice.",
    lat: 46.17372,
    lng: 19.97499,
  },
  {
    id: "tompa-kelebija",
    name: "Tompa / Kelebija",
    query: "Tompa Kelebija border crossing",
    pair: "HU-RS",
    openingHoursLabel: "Nonstop (24/7)",
    note: "Mezinárodní osobní i nákladní provoz.",
    lat: 46.15235,
    lng: 19.5776,
  },
  {
    id: "hercegszanto-backi-breg",
    name: "Hercegszántó / Bački Breg",
    query: "Hercegszanto Backi Breg border crossing",
    pair: "HU-RS",
    openingHoursLabel: "Nonstop (24/7)",
    note: "Osobní provoz; náklad do 3,5 t.",
    lat: 45.92015,
    lng: 18.93214,
  },
  {
    id: "bacsalmas-bajmok",
    name: "Bácsalmás / Bajmok",
    query: "Bacsalmas Bajmok border crossing",
    pair: "HU-RS",
    openingHoursLabel: "7:00–19:00 (V–VIII), 6:00–18:00 (IX–IV)",
    note: "Osobní provoz, bez autobusů.",
    lat: 45.96682,
    lng: 19.42493,
  },
  {
    id: "asotthalom-vinogradi",
    name: "Ásotthalom / Bački Vinogradi",
    query: "Asotthalom Backi Vinogradi border crossing",
    pair: "HU-RS",
    openingHoursLabel: "7:00–19:00 (V–VIII), 6:00–18:00 (IX–IV)",
    note: "Jen občané EU/EHP/CH/RS a rodinní příslušníci.",
    lat: 46.12339,
    lng: 19.85646,
  },
  {
    id: "tiszasziget-dala",
    name: "Tiszasziget / Đala",
    query: "Tiszasziget Djala border crossing",
    pair: "HU-RS",
    openingHoursLabel: "7:00–19:00 (V–VIII), 6:00–18:00 (IX–IV)",
    note: "Jen občané EU/EHP/CH/RS a rodinní příslušníci.",
    lat: 46.15479,
    lng: 20.10955,
  },
  {
    id: "kubekhaza-rabe",
    name: "Kübekháza / Rabe",
    query: "Kubekhaza Rabe border crossing",
    pair: "HU-RS",
    openingHoursLabel: "7:00–19:00 (V–VIII), 6:00–18:00 (IX–IV)",
    note: "Jen občané EU/EHP/CH/RS a rodinní příslušníci.",
    lat: 46.11166,
    lng: 20.25375,
  },
  {
    id: "bacsszentgyorgy-rastina",
    name: "Bácsszentgyörgy / Rastina",
    query: "Bacsszentgyorgy Rastina border crossing",
    pair: "HU-RS",
    openingHoursLabel: "7:00–19:00",
    note: "Jen občané EU/EHP/CH/RS a rodinní příslušníci, bez autobusů.",
    lat: 45.95962,
    lng: 19.03635,
  },

  // RS–BG
  {
    id: "gradina-kalotina",
    name: "Gradina / Kalotina (E80)",
    query: "Kalotina Gradina border crossing",
    pair: "RS-BG",
    openingHoursLabel: "Nonstop (24/7)",
    lat: 42.99932,
    lng: 22.82942,
  },
  {
    id: "strezimirovci",
    name: "Strezimirovci",
    query: "Strezimirovci border crossing",
    pair: "RS-BG",
    openingHoursLabel: "Nonstop (24/7)",
    lat: 42.79829,
    lng: 22.44377,
  },
  {
    id: "ribarci-oltomantsi",
    name: "Ribarci / Oltomantsi",
    query: "Oltomantsi Kyustendil border crossing",
    pair: "RS-BG",
    openingHoursLabel: "Nonstop (24/7)",
    note: "Osobní auta a dodávky.",
    lat: 42.318,
    lng: 22.346,
  },
  {
    id: "vrska-cuka",
    name: "Vrška Čuka / Vrashka Chuka",
    query: "Vrska Cuka border crossing",
    pair: "RS-BG",
    openingHoursLabel: "Nonstop (24/7)",
    lat: 43.84938,
    lng: 22.37979,
  },
  {
    id: "mokranje-bregovo",
    name: "Mokranje / Bregovo",
    query: "Bregovo Mokranje border crossing",
    pair: "RS-BG",
    openingHoursLabel: "Nonstop (24/7)",
    lat: 44.15189,
    lng: 22.63863,
  },

  // BG–MK
  {
    id: "gyueshevo-deve-bair",
    name: "Gjueshevo / Deve Bair (E871)",
    query: "Gyueshevo Deve Bair border crossing",
    pair: "BG-MK",
    openingHoursLabel: "Nonstop (24/7)",
    lat: 42.23602,
    lng: 22.47604,
  },
  {
    id: "zlatarevo-novo-selo",
    name: "Zlatarevo / Novo Selo",
    query: "Novo Selo North Macedonia Bulgaria border",
    pair: "BG-MK",
    openingHoursLabel: "Nonstop (24/7)",
    lat: 41.4128,
    lng: 22.8817,
  },
  {
    id: "stanke-lisichkovo",
    name: "Stanke Lisichkovo / Delčevo",
    query: "Stanke Lisichkovo border crossing",
    pair: "BG-MK",
    openingHoursLabel: "Nonstop (24/7)",
    lat: 41.977,
    lng: 22.86,
  },

  // MK–RS
  {
    id: "tabanovce-presevo",
    name: "Tabanovce / Preševo (E75)",
    query: "Tabanovce Presevo border crossing",
    pair: "MK-RS",
    openingHoursLabel: "Nonstop (24/7)",
    lat: 42.23838,
    lng: 21.70295,
  },
  {
    id: "pelince",
    name: "Pelince / Prohor Pčinjski",
    query: "Pelince border crossing North Macedonia",
    pair: "MK-RS",
    openingHoursLabel: "Nonstop (24/7)",
    lat: 42.28788,
    lng: 21.85715,
  },

  // NO–SE (customs, not passport)
  {
    id: "svinesund",
    name: "Svinesund (E6)",
    query: "Svinesund customs border Norway Sweden",
    pair: "NO-SE",
    openingHoursLabel: "Nonstop (clo; Schengen bez pasové kontroly)",
    lat: 59.09686,
    lng: 11.2651,
  },
  {
    id: "orje",
    name: "Ørje / Töcksfors",
    query: "Orje Tocksfors border crossing",
    pair: "NO-SE",
    openingHoursLabel: "Nonstop (clo; Schengen bez pasové kontroly)",
    lat: 59.48023,
    lng: 11.66016,
  },
  {
    id: "kornsjo",
    name: "Kornsjø / Nordby",
    query: "Kornsjo border crossing Norway Sweden",
    pair: "NO-SE",
    openingHoursLabel: "Otevírací doba cla ověřte na tolletaten.no",
    lat: 58.93193,
    lng: 11.6451,
  },
  {
    id: "umbukta",
    name: "Umbukta / Tärnaby (E12)",
    query: "Umbukta border crossing Norway Sweden",
    pair: "NO-SE",
    openingHoursLabel: "Nonstop (clo; Schengen bez pasové kontroly)",
    lat: 66.14871,
    lng: 14.57261,
  },
  {
    id: "junkerdal",
    name: "Junkerdal / Graddis",
    query: "Graddis Norway Sweden border",
    pair: "NO-SE",
    openingHoursLabel: "Nonstop (clo; Schengen bez pasové kontroly)",
    lat: 66.74232,
    lng: 15.73838,
  },
  {
    id: "storlien",
    name: "Storlien (E14)",
    query: "Storlien border crossing Norway Sweden E14",
    pair: "NO-SE",
    openingHoursLabel: "Nonstop (clo; Schengen bez pasové kontroly)",
    lat: 63.31626,
    lng: 12.09989,
  },
];
